### PR TITLE
default to placeholder

### PR DESCRIPTION
**Pull request by anandkumarpatel**
default to placeholder

Screen Shot 2022-07-10 at 6 31 59 PM
Screen Shot 2022-07-10 at 6 40 44 PM

re: #2

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @anandkumarpatel, I'll review the changes right away!

**Comment by anandkumarpatel** [comment]
Screen Shot 2022-07-10 at 6 31 59 PM

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @anandkumarpatel! You're now able to merge the PR.

**Pull request merged**
